test: add t1 which is copied from doc test of List
$ cargo miri test --test list
test t1 ... error: unsupported operation: can't call foreign function `rust_helper_krealloc_node_align` on OS `linux`
   --> /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/src/alloc/allocator.rs:115:13
    |
115 |             self.0(ptr.cast(), size, layout.align(), flags.0, nid.0).cast()
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unsupported operation occurred here
    |
    = help: this means the program tried to do something Miri does not support; it does not indicate a bug in the program
    = note: BACKTRACE on thread `t1`:
    = note: inside `linked_list_r4l_upstream::alloc::allocator::ReallocFunc::call` at /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/
src/alloc/allocator.rs:115:13: 115:69
note: inside `<linked_list_r4l_upstream::alloc::allocator::Kmalloc as linked_list_r4l_upstream::alloc::Allocator>::realloc`
   --> /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/src/alloc/allocator.rs:157:18
    |
157 |         unsafe { ReallocFunc::KREALLOC.call(ptr, layout, old_layout, flags, nid) }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `<linked_list_r4l_upstream::alloc::allocator::Kmalloc as linked_list_r4l_upstream::alloc::Allocator>::alloc`
   --> /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/src/alloc.rs:190:18
    |
190 |         unsafe { Self::realloc(None, layout, Layout::new::<()>(), flags, nid) }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `linked_list_r4l_upstream::alloc::Box::<linked_list_r4l_upstream::sync::arc::ArcInner<std::mem::MaybeUninit<t1::DTWrap<t1::A>>>,
linked_list_r4l_upstream::alloc::allocator::Kmalloc>::new_uninit`
   --> /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/src/alloc/kbox.rs:276:19
    |
276 |         let ptr = A::alloc(layout, flags, NumaNode::NO_NODE)?;
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `<linked_list_r4l_upstream::alloc::Box<linked_list_r4l_upstream::sync::arc::ArcInner<std::mem::MaybeUninit<t1::DTWrap<t1::A>>>, l
inked_list_r4l_upstream::alloc::allocator::Kmalloc> as linked_list_r4l_upstream::init::InPlaceInit<linked_list_r4l_upstream::sync::arc::ArcInn
er<std::mem::MaybeUninit<t1::DTWrap<t1::A>>>>>::try_init::<linked_list_r4l_upstream::alloc::AllocError, pin_init::__internal::InitClosure<{clo
sure@linked_list_r4l_upstream::sync::UniqueArc<t1::DTWrap<t1::A>>::new_uninit::{closure#1}}, linked_list_r4l_upstream::sync::arc::ArcInner<std
::mem::MaybeUninit<t1::DTWrap<t1::A>>>, linked_list_r4l_upstream::alloc::AllocError>>`
   --> /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/src/alloc/kbox.rs:476:9
    |
476 |         Box::<_, A>::new_uninit(flags)?.write_init(init)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `linked_list_r4l_upstream::sync::UniqueArc::<t1::DTWrap<t1::A>>::new_uninit`
   --> /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/src/sync/arc.rs:760:21
    |
760 |           let inner = KBox::try_init::<AllocError>(
    |  _____________________^
761 | |             try_init!(ArcInner {
762 | |                 refcount: Refcount::new(1),
763 | |                 data <- pin_init::uninit::<T, AllocError>(),
764 | |             }? AllocError),
765 | |             flags,
766 | |         )?;
    | |_________^
note: inside `<linked_list_r4l_upstream::sync::UniqueArc<t1::DTWrap<t1::A>> as linked_list_r4l_upstream::init::InPlaceInit<t1::DTWrap<t1::A>>>
::try_pin_init::<linked_list_r4l_upstream::error::Error, pin_init::__internal::InitClosure<{closure@/home/gh-zjp-CN/bugs-found/fix/linked_list
_r4l-upstream/pin-init/src/macros.rs:1264:20: 1264:67}, t1::DTWrap<t1::A>, linked_list_r4l_upstream::error::Error>>`
   --> /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/src/sync/arc.rs:714:9
    |
714 |         UniqueArc::new_uninit(flags)?.write_pin_init(init)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `linked_list_r4l_upstream::list::ListArc::<t1::DTWrap<t1::A>>::pin_init::<linked_list_r4l_upstream::error::Error, pin_init::__int
ernal::InitClosure<{closure@/home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/pin-init/src/macros.rs:1264:20: 1264:67}, t1::DTWrap<t1::A
>, linked_list_r4l_upstream::error::Error>>`
   --> /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/src/list/arc.rs:189:23
    |
189 |         Ok(Self::from(UniqueArc::try_pin_init(init, flags)?))
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `t1::DTWrap::<t1::A>::new`
   --> tests/list.rs:18:13
    |
 18 | /             ListArc::pin_init(
 19 | |                 try_pin_init!(Self {
 20 | |                     value,
 21 | |                     links <- ListLinksSelfPtr::new(),
 22 | |                 }),
 23 | |                 GFP_KERNEL,
 24 | |             )
    | |_____________^
note: inside `t1`
   --> tests/list.rs:58:20
    |
 58 |     list.push_back(DTWrap::new(A(15))?);
    |                    ^^^^^^^^^^^^^^^^^^
note: inside closure
   --> tests/list.rs:4:12
    |
  3 | #[test]
    | ------- in this attribute macro expansion
  4 | fn t1() -> Result<()> {
    |            ^^^^^^^^^^

$ cargo test --test list
error: linking with `cc` failed: exit status: 1
  |
  = note:  "cc" "/tmp/rustcnU6PUF/symbols.o" "<45 object files omitted>" "-Wl,--as-needed" "-Wl,-Bstatic" "<sysroot>/lib/rustlib/aarch64-unknown-linux-gn
u/lib/{libtest-*,libgetopts-*,librustc_std_workspace_std-*}.rlib" "/home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/target/debug/deps/{liblinked_l
ist_r4l_upstream-e4dea5cb1f9d9ff7,libbindings-7f4d313fd23c439b,libffi-f874a28251d3b0f5,libpin_init-13fe690f7aeb02bf}.rlib" "<sysroot>/lib/rustlib/aarch64
-unknown-linux-gnu/lib/{libstd-*,libpanic_unwind-*,libobject-*,libmemchr-*,libaddr2line-*,libgimli-*,libcfg_if-*,librustc_demangle-*,libstd_detect-*,libh
ashbrown-*,librustc_std_workspace_alloc-*,libminiz_oxide-*,libadler2-*,libunwind-*,liblibc-*,librustc_std_workspace_core-*,liballoc-*,libcore-*,libcompil
er_builtins-*}.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-L" "/tmp/rustcnU6PUF/raw-dylibs" "-Wl,--eh-frame-hdr" "-W
l,-z,noexecstack" "-L" "<sysroot>/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-o" "/home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/target/debug/d
eps/list-0d6530d83344344b" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: /usr/bin/ld: /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/target/debug/deps/list-0d6530d83344344b.8b7150dsfiqhq75e6in08av7f.0j3j995.
rcgu.o: in function `linked_list_r4l_upstream::sync::refcount::Refcount::dec_and_test':
          /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/src/sync/refcount.rs:104:(.text._ZN24linked_list_r4l_upstream4sync8refcount8Refcount12d
ec_and_test17h97c6d1d92ed50976E+0x18): undefined reference to `rust_helper_refcount_dec_and_test'
          /usr/bin/ld: /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/target/debug/deps/list-0d6530d83344344b.8b7150dsfiqhq75e6in08av7f.0j3j995.
rcgu.o: in function `linked_list_r4l_upstream::sync::refcount::Refcount::new':
          /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/src/sync/refcount.rs:29:(.text._ZN24linked_list_r4l_upstream4sync8refcount8Refcount3new
17hca89508d87c8399dE+0x44): undefined reference to `rust_helper_REFCOUNT_INIT'
          /usr/bin/ld: /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/target/debug/deps/list-0d6530d83344344b.ahfnkyn8dm3xdahi6cirldtig.0j3j995.
rcgu.o:(.data.rel.ro..Lanon.17a408d8bdcbcb46a88d5ececa6b936f.0+0x0): undefined reference to `rust_helper_krealloc_node_align'
          /usr/bin/ld: /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/target/debug/deps/liblinked_list_r4l_upstream-e4dea5cb1f9d9ff7.rlib(linked
_list_r4l_upstream-e4dea5cb1f9d9ff7.02qdtni77nwnlcg6ppqzlof58.04b4rcc.rcgu.o):(.data.rel.ro..Lanon.fdd3882a9a1c4aff820863e1e8fd2dd0.0+0x0): undefined ref
erence to `rust_helper_krealloc_node_align'
          /usr/bin/ld: /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/target/debug/deps/liblinked_list_r4l_upstream-e4dea5cb1f9d9ff7.rlib(linked
_list_r4l_upstream-e4dea5cb1f9d9ff7.axatqcwuw9q5cdko74m21afry.04b4rcc.rcgu.o): in function `linked_list_r4l_upstream::error::Error::name':
          /home/gh-zjp-CN/bugs-found/fix/linked_list_r4l-upstream/src/error.rs:179:(.text._ZN24linked_list_r4l_upstream5error5Error4name17h65b165c9241001
fdE+0x3c): undefined reference to `errname'
          collect2: error: ld returned 1 exit status

  = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/buil
d-scripts.html#rustc-link-lib)